name: Purge Cloudflare Cache

on:
  workflow_dispatch:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:

  purge:
    name: Purge changed file URLs cache
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Purge Cloudflare cache for changes
        env:
          CLOUDFLARE_ZONE_ID: ${{ secrets.CLOUDFLARE_ZONE_ID }}
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          GITHUB_EVENT_BEFORE: ${{ github.event.before }}
        run: node purge.js
